spring.application.name=chatapp
# ==============================
# DATABASE CONNECTION
# ==============================
# Đã thêm cấu hình hỗ trợ gõ tiếng Việt có dấu (characterEncoding=UTF-8)
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==============================
# JPA / HIBERNATE
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# (Tùy chọn) Dòng này giúp các câu lệnh SQL in ra terminal nhìn đẹp mắt, dễ đọc hơn
spring.jpa.properties.hibernate.format_sql=true

jwt.secret-key=yfH1x5azlrE4we6XsVsZq3rd/0pdv15bm966IauAclguJzbzMEOspCAyoxHoVzfiKgn9d8eol5Qwk45Nw0qlpyDoDKKGByc6+Cz0yFRb9O0=
spring.jpa.properties.hibernate.type.json_format_mapper=com.oqnsuthyz.chatapp.config.CustomHibernateJsonFormatter
